#!/usr/bin/env python3
"""Bake a benchmark run into the self-contained dashboard.

The dashboard (bench/deploy/dashboard.html) computes its charts, headline
tiles and summary entirely from data — nothing is hand-written. This regenerates
the embedded snapshot between the __BENCH_DATA_START__ / __BENCH_DATA_END__ markers
from combined.json, so the standalone file always matches the latest run. (When
served over http the page also reloads combined.json live; this keeps the file:// /
hosted copy in sync too.)

    bench/gen_dashboard.py [combined.json] [results-bonsaigrid-fair.json]

Run automatically at the end of bench/run-all-isolated.sh.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
HTML = os.path.join(HERE, "deploy", "dashboard.html")
START = "// __BENCH_DATA_START__"
END = "// __BENCH_DATA_END__"
ORDER = [("bonsaigrid", "BG"), ("hazelcast", "HZ"), ("redis", "RD"), ("memcached", "MC")]


def arr(stages, pick):
    return "[" + ",".join(repr(pick(s)) for s in stages) + "]"


def backend_js(var, name, stages):
    if not stages:
        # keep the const defined so DATASET/{BG,HZ,RD,MC} references never break
        return (f"const {var} = {{ // {name} (absent from this run)\n"
                "  rps:[], set:{p50:[],p90:[],p99:[]}, get:{p50:[],p90:[],p99:[]}, cpu:[], mem:[],\n};")
    def p(op, k):
        return arr(stages, lambda s: s[op][k])
    cpu = arr(stages, lambda s: s["cpu"]["avg_pct"]) if stages[0].get("cpu") else "[]"
    mem = arr(stages, lambda s: s["mem"]["avg_mb"]) if stages[0].get("mem") else "[]"
    return (
        f"const {var} = {{ // {name}\n"
        f"  rps:{arr(stages, lambda s: round(s['set']['rps']))},\n"
        f"  set:{{p50:{p('set','p50_us')}, p90:{p('set','p90_us')}, p99:{p('set','p99_us')}}},\n"
        f"  get:{{p50:{p('get','p50_us')}, p90:{p('get','p90_us')}, p99:{p('get','p99_us')}}},\n"
        f"  cpu:{cpu}, mem:{mem},\n}};"
    )


def build_block(combined, fair):
    lines = [
        START + "  (generated by bench/gen_dashboard.py — do not hand-edit)",
        "// Embedded snapshot of the latest run. When served over http the page also reloads",
        "// combined.json live. Regenerate: bench/gen_dashboard.py bench/loadgen/combined.json",
    ]
    present = []
    for key, var in ORDER:
        stages = combined.get(key) or []
        if stages:
            present.append(key)
        lines.append(backend_js(var, var, stages))
        if var == "BG":
            native = [round(s["set"]["rps"]) for s in (fair.get("stages") or [])] if fair else []
            lines.insert(len(lines), "let BG_NATIVE_RPS = "
                         + ("[" + ",".join(map(str, native)) + "]" if native else "[]") + ";")
    mism = sum(int(s.get("mismatch") or 0) for st in combined.values() for s in (st or []))
    lines.append(f"let TOTAL_MISMATCH = {mism};")
    lines.append("const BAKED_PRESENT = " + json.dumps(present) + ";")
    lines.append(END)
    return "\n".join(lines), present, mism


def main():
    combined_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "loadgen", "combined.json")
    fair_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, "loadgen", "results-bonsaigrid-fair.json")
    combined = json.load(open(combined_path))
    fair = json.load(open(fair_path)) if os.path.exists(fair_path) else None

    html = open(HTML).read()
    i, j = html.find(START), html.find(END)
    if i < 0 or j < 0:
        sys.exit(f"markers not found in {HTML}")
    block, present, mism = build_block(combined, fair)
    html = html[:i] + block + html[j + len(END):]
    open(HTML, "w").write(html)
    warn = "" if mism == 0 else f"  *** {mism} MISMATCHES — run invalid ***"
    print(f"baked {len(present)} backends into {os.path.relpath(HTML)} (mismatch={mism}){warn}")


if __name__ == "__main__":
    main()
